services:
  homeos:
    build:
      context: .
      dockerfile: apps/bots/telegram/Dockerfile

    container_name: homeos

    env_file:
      - .env

    volumes:
      - ./data:/app/data

    ports:
      - "127.0.0.1:8080:8080"

    restart: unless-stopped